### ISSUE TITLE
Required MPI3 support

### ISSUE THREAD

**Issue by devinamatthews** [solomonik/ctf#14]
Currently OpenMPI 1.6.5 (and possible other pre-MPI3 libs) can't compile CTF. We should clarify:

1. If MPI3 support is required (or what MPI3 features are required)?
2. What minimum version of OpenMPI/MPICH etc. is required?

(Note that OpenMPI 1.6.5 did work until recently, so perhaps full MPI3 support isn't necessarily required?)

**Comment by jeffhammond** [comment]
We can rely upon `MPI_VERSION` and `MPI_SUBVERSION`, although this is not always reliable, both because implementers don't wait until they have all of MPI x.y before setting those symbols to x and y, respectively, and because implemented features don't always work correctly.

The other option is to switch to a real Autotools build system and have `configure` tests for the exact set of MPI features we use.

**Comment by solomonik** [comment]
I think currently all CTF MPI usage is quite basic (no one sided communication or asynchronous collectives at the moment), so MPI 3 support is not required, but I don't know exactly what version is required.  If you can confirm that OpenMPI works now that we switched the datatype nomenology I will close this.
