### ISSUE TITLE
-std=c++11 missing with clang on OSX

### ISSUE THREAD

**Issue by devinamatthews** [solomonik/ctf#9]
The -std=c++11 flag is missing in config.mk, even though C++11 is checked and passes during configure. Specs:

OSX 10.11
clang 3.5.0 (homebrew)
openmpi 1.10

**Comment by solomonik** [comment]
Strange that it passes (presumably without saying "tacking on -std=c++0x"?), then fails at compile time (I tried to put the same C++11 usage in the test as used in the code).  I added the flag as a default for Apple.  Please let me know if that fixes things (not closing for now).  

I also noticed that clang with optimizations seems to be failing on the 3D DFT test (although I thought clang had been working fine not long ago, but maybe I was checking with -O0), likely due to the use of std::complex< long double > in that example.  Valgrind gives "general protection fault error", which I've never seen before.  I am guessing AQ will still work.  Will revisit this.

**Comment by devinamatthews** [comment]
Correct, is does not say "tacking on...". I steer clear of long double, 
so I'll keep my fingers crossed.
